name: Kick Bot Runner

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  # تنظیم زمان‌بندی برای اجرا هر ۵ ساعت و ۴۵ دقیقه (برای جلوگیری از توقف ۶ ساعته)
  schedule:
    - cron: "45 */5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 355 # توقف خودکار قبل از محدودیت ۶ ساعته گیت‌هاب

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # نصب کتابخانه مخصوص کدی که فرستادید (TeleBot)
        run: |
          pip install --upgrade pip
          pip install pyTelegramBotAPI

      - name: Run Bot
        # انتقال توکن از تنظیمات گیت‌هاب به فایل پایتون
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
